name       : http-prompt
version    : 0.11.2
release    : 4
source     :
    - https://github.com/eliangcs/http-prompt/archive/v0.11.2.tar.gz : 88db627d7bdd73be0889ac829ce276e4fe42f39a20681b534a9fa731d0aa2e2f
license    : MIT
component  : network.clients
summary    : An interactive command-line HTTP client featuring autocomplete and syntax
    highlighting
description: |
    An interactive command-line HTTP client featuring autocomplete and syntax highlighting
builddeps  :
    - httpie
    - pygments
    - python-click
    - python-parsimonious
    - python-prompt-toolkit
    - python-setuptools
    - python-six
rundeps    :
    - httpie
    - pygments
    - python-click
    - python-parsimonious
    - python-prompt-toolkit
    - python-six
setup      : |
    %python3_setup
install    : |
    %python3_install
